config/routes.rb
Abctech::Application.routes.draw do
  root :to => "candidates#index"
  get '/candidates/show' => 'candidates#show'
  get '/candidates/load' => 'candidates#load'
  get '/candidates/new' => 'candidates#new'
  get '/candidates/upload_picture' => 'candidates#upload_picture'
  post '/candidates/create' => 'candidates#create'
  post '/candidates/update_picture' => 'candidates#update_picture'
end

app/models/candidate.rb
class Candidate
  include HTTParty
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming
  base_uri 'http://siam.dev.abctech-thailand.com/candidate/rest/candidateService/'
  format :json

  attr_accessor :name, :age, :gender, :uuid

  validates_presence_of :name, :age, :gender

  def initialize(attr = {})
    self.name, self.age, self.gender, self.uuid = attr[:name], attr[:age], attr[:gender], attr[:uuid]
  end

  def save
    if valid?
      payload = { :name => name, :age => age, :gender => gender }
      response = post('/save.json', :body => payload.to_json, :headers => {"Content-Type" => "application/json"}).parsed_response
      self.uuid = response["uuid"]

      return response
    else
      false
    end
  end

  class << self
    def load(uuid)
      response = get("/load/#{uuid}.json").parsed_response if uuid
    end

    def upload_picture(attr = {})
      picture = Base64.encode64(File.open(attr[:imageBase64]).read)
      payload = { :uuid => attr[:uuid], :imageBase64 => picture }
      response = put("/upload/image/#{attr[:uuid]}.json", :body => payload.to_json, :headers => {"Content-Type" => "application/json"}).parsed_response
    end

    def view_link(uuid)
      "http://siam.dev.abctech-thailand.com/candidate/view.html?uuid=#{uuid}" if uuid
    end


  end

  private

  def get(method, opts={})
    begin
      response = self.class.get(method, opts)
    rescue Timeout::Error
      raise "ABC tech candidate didn't respond in time"
    end

    response["code"] == 200 ? response = response.parsed_response : response = response.parsed_response["errorMessage"]
    return response
  end

  def post(method, opts={})
    begin
      response = self.class.post(method, opts)
    rescue Timeout::Error
      raise "ABC tech candidate didn't respond in time"
    end

    return response


    response.code == 200 ? response = response : response = response.message
    return response
  end

  def put(method, opts={})
    begin
      response = self.class.put(method, opts)
    rescue Timeout::Error
      raise "ABC tech candidate didn't respond in time"
    end

    response["code"] == 200 ? response = response.parsed_response : response = response.parsed_response["errorMessage"]
    return response
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController

  def index

  end

  def show
    candidate = Candidate.load(params[:uuid])
    @candidate = Candidate.new({:name => candidate["name"], :age => candidate["age"], :gender => candidate["gender"], :uuid => candidate["uuid"]})
    @view_link = Candidate.view_link(candidate["uuid"])

    if candidate["status"] == -1
      redirect_to '/', :notice => "This UUID is not valid, please try again."
    else
      @notice = params[:notice]
    end
  end

  def new

  end

  def create
    @candidate = Candidate.new(:name => params[:name], :age => params[:age], :gender => params[:gender])

    respond_to do |format|
      if @candidate.save["status"] == 1
        format.html { redirect_to action: "show", notice: "Candidate was successfully created.", :uuid => @candidate.uuid }
      else
        format.html { render action: "new" }
      end
    end
  end

  def load
    candidate = Candidate.new(params[:uuid])
    @candidate = candidate.save
    redirect_to '/', :notice => "This UUID is not valid, please try again." if not @candidate
  end

  def upload_picture

  end

  def update_picture
    @candidate = Candidate.upload_picture(:uuid => params[:uuid], :imageBase64 => params[:imageBase64].tempfile) if not params[:imageBase64].blank?

    respond_to do |format|
      if not params[:imageBase64].blank? and @candidate["status"] == 1
        format.html { redirect_to action: "show", notice: "Candidate was successfully updated.", :uuid => params[:uuid] }
      else
        format.html { redirect_to '/candidates/upload_picture', :notice => "Invalid data, please try again." }
      end
    end

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/views/candidates/index.html.erb
<div class="hero-unit">
  <h2>Please give me your UUID.</h2>
  <p>This application is prepared exclusively for Tuan Tran.</p>
  <% if flash[:notice] %>
    <div class="alert alert-error">
      <%= flash[:notice] %>
    </div>
  <% end %>
  <p>
  <form id="search" class="form-search" action="/candidates/show" method="get">
  <div class="input-append">
    <input id="uuid" placeholder="1249dce6-f378-443c-a83f-6c13c27d2ff4" type="text" name="uuid" class="span5 input-large-search">
    <button type="submit" class="btn btn-primary btn-large">Hit me!</button>
  </div>
  </form>
  </p>

</div>

app/views/candidates/load.html.erb
<div class="hero-unit">
  <% if @notice %>
    <div class="alert alert-error">
    <%= @notice %>
  </div>
<% end %>
  <h2>UUID <%= @candidate["uuid"]%></h2>
  <% if @notice %>
    <div class="alert alert-success">
    <%= @notice %>
  </div>
<% end %>
  <p>Name: <%=@candidate.name%></p>
  <p>Age: <%=@candidate.age%></p>
  <p>Gender: <%=@candidate.gender%></p>
  <p>View URL: <a href="<%= @candidate%>">link</a></p>

</div>

app/views/candidates/new.html.erb
<div class="container">

  <div class="well">    
    <form id="signup" class="form-horizontal" method="post" action="/candidates/create">
      <legend><h2>New Candidate</h2></legend>
      <div class="control-group">
        <label class="control-label control-label-new">Name</label>
        <div class="controls controls-new">
          <div class="input-prepend">
            <input type="text" class="input input-large-new" id="name" name="name" placeholder="Ryan Bates">
          </div>
        </div>
      </div>
      <div class="control-group ">
        <label class="control-label control-label-new">Age</label>
        <div class="controls controls-new">
          <div class="input-prepend">
            <input type="text" class="input input-large-new" id="age" name="age" placeholder="23">
          </div>
        </div>
      </div>
      <div class="control-group">
        <label class="control-label control-label-new">Gender</label>
        <input type="hidden" id="sex" name="gender" value="" />
        <div class="controls controls-new">
          <p>
          <div id="gender" name="gender" class="btn-group" data-toggle="buttons-radio">
            <button type="button" class="btn btn-large btn-info btn-gender">Male</button>
            <button type="button" class="btn btn-large btn-info btn-gender">Female</button>
          </div>
          </p>
        </div>
      </div>
      <div class="control-group">
        <div class="controls controls-center">
          <button type="submit" class="btn btn-large btn-success" rel="tooltip" title="first tooltip">Create New Candidate</button>
        </div>
      </div>
    </form>
  </div>
</div>

app/views/candidates/show.html.erb
<div class="hero-unit">
  <h2>UUID: <%= @candidate.uuid%></h2>
  <% if @notice %>
    <div class="alert alert-success">
      <%= @notice %>
  </div>
  <% end %>
  <p>Name: <%=@candidate.name%></p>
  <p>Age: <%=@candidate.age%></p>
  <p>Gender: <%=@candidate.gender%></p>
  <p>View URL: <a target="_blank" href="<%= @view_link %>"><%= @view_link %></a></p>

</div>

app/views/candidates/upload_picture.html.erb
<div class="container">
  <div class="well">
    <% if flash[:notice] %>
      <div class="alert alert-error">
      <%= flash[:notice] %>
    </div>
  <% end %>    
    <form id="upload-picture" class="form-horizontal" method="post" action="/candidates/update_picture" enctype="multipart/form-data">
      <legend><h2>Upload Picture</h2></legend>
      <div class="control-group">
        <label class="control-label control-label-new">UUID</label>
        <div class="controls controls-new">
          <div class="input-prepend">
            <input type="text" class="input input-large-new" id="uuid" name="uuid" placeholder="1249dce6-f378-443c-a83f-6c13c27d2ff4">
          </div>
        </div>
      </div>
      <div class="control-group ">
        <div style="position:relative;">
          <a class='btn' href='javascript:;'> Choose Picture
            <input id="fileupload" type="file" style='position:absolute;z-index:2;top:0;left:0;filter: alpha(opacity=0);-ms-filter:"progid:DXImageTransform.Microsoft.Alpha(Opacity=0)";opacity:0;background-color:transparent;color:transparent;' name="imageBase64" size="40"  onchange='$("#upload-file-info").html($(this).val());'>
          </a>
          &nbsp;
          <span class='label label-info' id="upload-file-info"></span>
        </div>
      </div>
    </div>
  </div>
  <div class="control-group">
    <div class="controls controls-center">
      <button type="submit" class="btn btn-large btn-success" rel="tooltip" title="first tooltip">Submit</button>
    </div>
  </div>
</form>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Candidate app</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "jquery.validate.js" %>


  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="/">ABC Tech</a>
        <div class="nav-collapse">
          <ul class="nav">
            <li><%= link_to "Load candidate", root_path %></li>
            <li><%= link_to "New candidate", candidates_new_path %></li>
            <li><%= link_to "Upload picture", candidates_upload_picture_path %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <%= yield %>
    </div>
  </div>
</body>
</html>